### ISSUE TITLE
windows: fork() function is unimplemented

### ISSUE THREAD

**Issue by isimmons** [vagrant-landrush/landrush#16]
First time using this and not sure if I'm even using it right :-)

Here is my vagrant file
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise32"
 
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.landrush.enable

  config.vm.hostname = 'myhost.vagrant.dev'

  #config.vm.network :forwarded_port, guest: 80, host: 3000

  #config.vm.provision :shell, :path => "bootstrap.sh"
 
end
```
This is the output
```
  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise32'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] [landrush] virtualbox requires an additional private network; adding it
[default] [landrush] starting dns server
[landrush] Starting daemon...
[default] Destroying VM and associated drives...
C:/Users/lotus/.vagrant.d/gems/gems/rexec-1.5.2/lib/rexec/daemon/controller.rb:75:in `fork': fork() function is unimplemented on this machine
 (NotImplementedError)
        from C:/Users/lotus/.vagrant.d/gems/gems/rexec-1.5.2/lib/rexec/daemon/controller.rb:75:in `start'
        from C:/Users/lotus/.vagrant.d/gems/gems/rexec-1.5.2/lib/rexec/daemon/base.rb:129:in `start'
        from C:/Users/lotus/.vagrant.d/gems/gems/landrush-0.7.0/lib/landrush/action/setup.rb:39:in `start_server'
        from C:/Users/lotus/.vagrant.d/gems/gems/landrush-0.7.0/lib/landrush/action/setup.rb:20:in `pre_boot_setup'
        from C:/Users/lotus/.vagrant.d/gems/gems/landrush-0.7.0/lib/landrush/action/setup.rb:8:in `block in call'
        from C:/Users/lotus/.vagrant.d/gems/gems/landrush-0.7.0/lib/landrush/action/common.rb:21:in `handle_action_stack'
        from C:/Users/lotus/.vagrant.d/gems/gems/landrush-0.7.0/lib/landrush/action/setup.rb:7:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/share_folders.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/clear_shared_folders.rb:12:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:11:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/nfs.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/prune_nfs_exports.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:118:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/provision.rb:54:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/set_name.rb:47:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/machine.rb:147:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'      
```

On Windows 7 pro 64bit but running 32bit vagrant and virtualbox
ruby 1.9.3

**Comment by tomaszbrunarski** [comment]
+1, is this going to be released any time soon?

**Comment by phinze** [comment]
Hey folks,

Sorry for the lack of progress on Windows support. I'm still without a Windows machine to test on. It's sort of a core problem in the library we use:

```
[landrush] Starting daemon...
ERROR warden: Error occurred: fork() function is unimplemented on this machine
```

Looks like I might be able to boot a Windows Server machine on Azure - I might try and investigate that to see if I can get vagrant up and running out in the cloud. :cloud: Anybody with a windows dev environment and some knowledge is welcome to chime in here though! :grinning:

**Comment by ghuntley** [comment]
Yo @phinze you can use https://github.com/joefitzgerald/packer-windows to build yourself a windows vmware/vbox machine for vagrant. It will automatically download, configure, install using an evaluation edition.

    # packer build windows_2012_r2_core.json

Boop boop, done :rocket:

**Comment by seanbuscay** [comment]
+1 To subscribe and also offer to be a tester on Windows 8.

**Comment by tomaszbrunarski** [comment]
I can test on win7 64bit

**Comment by iwxfer** [comment]
Same error here Windows 7 64bit. Any suggestion to fix? I know some Ruby but new with Vagrant.

**Comment by DuoKristina** [comment]
+1 - WIndows 8.1 here

**Comment by phinze** [comment]
Thanks to @ghuntley I did get a windows dev environment up and running recently!

I'll see if I can poke at landrush on windows this weekend. :dancer:

**Comment by ghuntley** [comment]
:dancers:

**Comment by robmpreston** [comment]
any luck on this? same problem

**Comment by stewest** [comment]
+1  WIndows 7 64bit

**Comment by wazoo** [comment]
I was having this error on Windows 8.1 as well with landrush.  I don't think fork() is implemented on windows at all so need a windows specific way to spawn the background process.

**Comment by v6** [comment]
// , I've run into a similar issue. 

I got the following chain of errors: 

.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/Users/nbasanes/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `start'
        from C:/Users/nbasanes/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/base.rb:129:in `start'
        from C:/Users/nbasanes/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/setup.rb:49:in `start_server'
        from C:/Users/nbasanes/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/setup.rb:23:in `pre_boot_setup'
        from C:/Users/nbasanes/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/setup.rb:8:in `block in call'
        from C:/Users/nbasanes/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/common.rb:22:in `handle_action_stack'
        from C:/Users/nbasanes/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/setup.rb:7:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/nfs/action_cleanup.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in `handle'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in `block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/set_name.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_check_outdated.rb:68:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by CruzanCaramele** [comment]
I Just ran into the same issue on Windows 7 when trying to push my vagrant box to atlas : 

hp (master *) Modern_Ops $ **vagrant push**
c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/safe_exec
.rb:22:in `fork': fork() function is unimplemented on this machine (NotImplement
edError)
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/u
til/safe_exec.rb:22:in `exec'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/pushe
s/atlas/push.rb:35:in `execute'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/pushe
s/atlas/push.rb:17:in `push'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/e
nvironment.rb:567:in `push'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/comma
nds/push/command.rb:28:in `execute'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/c
li.rb:42:in `execute'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/e
nvironment.rb:301:in `cli'
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:1
74:in `<main>'

**Comment by wandl** [comment]
+1 Any progress on this I am getting same error on windows 7, works fine on my Mac but when trying to setup development environment for other developers I am at a stand still with this error, any help appreciated.

**Comment by starise** [comment]
Sadly, same error here

```
[landrush] Starting daemon...
C:/Users/Andrea/.vagrant.d/gems/gems/rexec-1.6.3/lib/rexec/daemon/controller.rb:75:in `fork':
fork() function is unimplemented on this machine (NotImplementedError)
...
```

**Comment by aldialimucaj** [comment]
+1

**Comment by raupie** [comment]
I got this error and it went away when I uninstalled the vagrant-dns plugin.

**Comment by hferentschik** [comment]
FYI, the problem is not only with the use of `fork()`. I was able to make Landrush work by replacing Rexec with ChildProcess (still some work to do for properly stopping the daemon on Windows). See also https://github.com/hferentschik/landrush/tree/childprocess. 

However, there is yet another issue. As of RubyDNS 0.9.x (used by Landrush as basic DNS server), RubyDNS relies on celluloid-dns resp celluloid-io. Using Celluloid on Windows leads unfortunately to dead locks. See also - https://github.com/celluloid/celluloid-io/issues/74. I was seeing the described deadlocks as well and afaiu it is not sure whether Celluloid works in Windows at all.

I was able to work around it, by reverting RubyDNS to a 0.8.x version which is still based on EventMachine (https://github.com/hferentschik/landrush/commit/905abf2d80ee5cadbf75f29b230f09597413e348). With this additional change Landrush runs under Windows as well.

**Comment by v6** [comment]
// , This issue is still open. 

I think the message is clear. 

Windows can go `fork()` itself.

**Comment by strzibny** [comment]
@hferentschik & others: I suggest to to use the ChildProcess patch and downgrading RubyDNS. Can you prepare a PR for others to test?

**Comment by hferentschik** [comment]
> I think the message is clear.
> Windows can go fork() itself. 

I am not sure which message you are referring to, but afaiu there is no true `fork` on Windows and there will never be. At least not in the POSIX sense. The _win32-process_ implemented a `fork`, but it was just a simulation of the `fork` behavior. And in fact _win32-process_ removed the method again. From its homepage:

> Removal of Process.fork in release 0.7.0
> The Process.fork method was originally experimental but it has never
> been particularly useful in practice. On top of that, it required special
> implementations of the Process.waitXXX methods, so it was a maintenance
> issue as well.
  
So really, to have a solution which works for Windows as well as Unix, one needs to either switch to Ruby's `Process.spawn` for both cases or do some differentiation between the operating systems and use the `fork` approach on Unix and `CreateProcess` on Windows. This differentiation is for example offered by the _ChildProcess_ gem.

**Comment by hferentschik** [comment]
> @hferentschik & others: I suggest to to use the ChildProcess patch and downgrading RubyDNS.

+1 My vote as well :-)

> Can you prepare a PR for others to test?

Will do.

**Comment by ioquatix** [comment]
Unfortunately `fork` is not supported on Windows, and thus starting a daemon process in the unix sense is impossible. Process.spawn doesn't really have the desired behaviour. For RubyDNS 2.0, this is something that would need to be addressed in https://github.com/ioquatix/process-daemon

**Comment by hferentschik** [comment]
I created a pull request with a first stab on getting Landrush to work on all OSes. Tested on OS X and Windows 10 so far - https://github.com/phinze/landrush/pull/154.

**Comment by hferentschik** [comment]
@ioquatix

> Unfortunately fork is not supported on Windows,

Correct

> and thus starting a daemon process in the unix sense is impossible

I disagree. Starting a daemon process even on Linux does not require a POSIX `fork`. It is just one (maybe a bit simpler) way of doing it. 

> Process.spawn doesn't really have the desired behavior. 

Sure it does. I can start a child process and record its pid while letting the parent process exit. Exactly what I need. What is in your opinion missing? See also https://github.com/phinze/landrush/pull/154.

> this is something that would need to be addressed in https://github.com/ioquatix/process-daemon

True. Note, however, that Landrush did not rely on the RubyDNS server capabilities. It used the `rexec` gem instead. The bigger problems is that the even framework on which RubyDNS relies since 0.9 (Celluloid), does not properly work on Windows and causes the event loop to hang. For this reason, one needs as an additional change on top of the `fork` to `spawn` switch, downgrade to RubyDNS 0.8.x. This version is based on `evenmachine` which works across all OSes.

**Comment by CruzanCaramele** [comment]
i tried this on cygwin but unfortunately the same error comes up

**Comment by ioquatix** [comment]
it sounds like we should try to add a portable daemon mode to process-daemon. Perhaps Process#spawn can do it.

**Comment by hferentschik** [comment]
@CruzanCaramele 

> i tried this on cygwin but unfortunately the same error comes up

When did you try and how? I (force pushed) a couple of changes during the last days, so you might have something which did not work. In particular there was a problem on Linux. That said, the branch I am working on does not contain any usage of `fork` anymore, just `spawn`. So, if you really still see the original error, my guess is you somehow still use an old version. To try this you need to checkout this feature branch - https://github.com/hferentschik/landrush/tree/issue-16-spawn - and built your gem of it. Then install it using `vagrant plugin install <path to built gem>.

**Comment by hferentschik** [comment]
> sounds like we should try to add a portable daemon mode to process-daemon

+1

> Perhaps Process#spawn can do it.

Yes it can. This is how I solved the problem for this issue. See also - https://github.com/hferentschik/landrush/commit/9523710f9771a08fd2b2d53f8de7373fca6c0860#diff-695e5af033f2e918c112401dcbf9bfb1R63

**Comment by x1x** [comment]
@hferentschik If this is fixed why is it still not merged into the vagrant repo? Sorry if I am missing something simple, but it is just strange still to have this issue occuring with vagrant when solution seems to be out there.

**Comment by hferentschik** [comment]
>  If this is fixed why is it still not merged into the vagrant repo? 

It took time to get everyone on board with this. I think we have achieved this now. I am hoping to get this merged this week, latest next.

**Comment by hferentschik** [comment]
Resolved.

**Comment by benjie** [comment]
Awesome work resolving this! When's the release including this due to go out?

**Comment by tom-sherman** [comment]
Hi, I'm still getting this issue on Windows is this expected?

```
C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/npm-pipeline-rails-1.8.0/lib/npm-pipeline-rails/railtie.rb:24:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/npm-pipeline-rails-1.8.0/lib/npm-pipeline-rails/railtie.rb:24:in `background'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/npm-pipeline-rails-1.8.0/lib/npm-pipeline-rails/railtie.rb:67:in `block (2 levels) in <class:Railtie>'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/npm-pipeline-rails-1.8.0/lib/npm-pipeline-rails/railtie.rb:66:in `each'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/npm-pipeline-rails-1.8.0/lib/npm-pipeline-rails/railtie.rb:66:in `block in <class:Railtie>'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/initializable.rb:30:in `run'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from C:/tools/ruby23/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/application.rb:352:in `initialize!'
        from C:/Users/Tom/Documents/jooktube/config/environment.rb:5:in `<top (required)>'
        from C:/Users/Tom/Documents/jooktube/config.ru:3:in `require_relative'
        from C:/Users/Tom/Documents/jooktube/config.ru:3:in `block in <main>'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from C:/Users/Tom/Documents/jooktube/config.ru:in `new'
        from C:/Users/Tom/Documents/jooktube/config.ru:in `<main>'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/server.rb:84:in `app'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/server.rb:148:in `log_to_stdout'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/server.rb:102:in `start'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:85:in `server'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
